# Generated by Django 3.2.5 on 2021-11-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectviewed',
            name='actions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
