# Generated by Django 3.0.6 on 2021-09-14 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('address', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='users/user_image/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('gender', models.TextField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], null=True)),
                ('dob', models.CharField(blank=True, max_length=25, null=True)),
                ('education', models.CharField(default=None, max_length=100, null=True)),
                ('surname', models.CharField(default=None, max_length=254, null=True)),
                ('last_name', models.CharField(default=None, max_length=254, null=True)),
                ('first_name', models.CharField(default=None, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('total_questions', models.IntegerField(default=0)),
                ('total_upvotes', models.IntegerField(default=0)),
                ('total_downvotes', models.IntegerField(default=0)),
                ('total_answers', models.IntegerField(default=0)),
                ('ts_rank', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(blank=True, max_length=300, null=True)),
                ('dial', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('regions', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='StateProvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Countries')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='ResetRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(auto_now=True)),
                ('consumed', models.BooleanField(default=False)),
                ('use_case', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reset Request',
                'verbose_name_plural': 'Reset Requests',
            },
        ),
        migrations.CreateModel(
            name='OtherRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_type', models.CharField(max_length=100)),
                ('details', models.CharField(default=None, max_length=254, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Other Request',
                'verbose_name_plural': 'Other Requests',
            },
        ),
        migrations.CreateModel(
            name='LoginLogoutFail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(default='Non-Mobile', max_length=254)),
                ('login', models.BooleanField(default=False)),
                ('login_time', models.DateTimeField(default=None, null=True)),
                ('logout', models.BooleanField(default=False)),
                ('logout_time', models.DateTimeField(default=None, null=True)),
                ('failed_login', models.BooleanField(default=False)),
                ('failed_login_time', models.DateTimeField(default=None, null=True)),
                ('message', models.TextField(default=None, null=True)),
                ('spare0', models.CharField(default=None, max_length=100, null=True)),
                ('spare1', models.CharField(default=None, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LoginLogoutFailures',
                'verbose_name_plural': 'LoginLogoutFailures',
            },
        ),
        migrations.CreateModel(
            name='DeviceId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_type', models.CharField(default='Android', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('deactivate_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device ID',
                'verbose_name_plural': 'Device IDs',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(default='Android', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('spare', models.CharField(default=None, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Countries'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
