# Generated by Django 3.2.11 on 2022-01-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211214_1343'),
        ('users', '0004_auto_20220117_1806'),
    ]

    operations = [
    ]
