# Generated by Django 3.2.11 on 2022-01-18 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220117_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificationmodels',
            options={'verbose_name': 'User Certification', 'verbose_name_plural': 'User Certifications'},
        ),
        migrations.AlterModelOptions(
            name='projectsmodels',
            options={'verbose_name': 'User Project', 'verbose_name_plural': 'User Project'},
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='followers',
            new_name='follow',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='follower'),
        ),
    ]
