# Generated by Django 3.0.6 on 2021-09-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20210916_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='total_answers',
            field=models.IntegerField(default=0),
        ),
    ]
