# Generated by Django 3.2.8 on 2021-10-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_total_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'TagsQuestion',
                'verbose_name_plural': 'TagsQuestions',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(related_name='question_tags', to='questions.TagsQuestions'),
        ),
    ]
