# Generated by Django 3.2.8 on 2021-10-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20211015_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagsquestions',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
